### ISSUE TITLE
Link errado no Ep. 12

### ISSUE THREAD

**Issue by elyssonmr** [sudocast/episodios#5]
Bom dia!
Existe um link errado no [episódio 12](http://sudocast.com.br/portfolio-items/ep-0012-nao-deixe-o-samba-morrer/). O link para o Castálio Podcast aponta para o Serenata de Amor.
O Link correto: [Castalio Avelino](https://castalio.info/episodio-64-thiago-avelino-openmining-e-sambaporno.html)

**Comment by perylemke** [comment]
Link ajustado :)

**Comment by elyssonmr** [comment]
Já foi feito o deploy dessa alteração?
